// Central place for metro stations in this demo.
// Derived from backend `lines` + station aliasing.
export const ALL_STATIONS = [
  "Dum Dum",
  "Belgachia",
  "Shyambazar",
  "Sovabazar",
  "Girish Park",
  "MG Road",
  "Central",
  "Chandni Chowk",
  "Esplanade",
  "Park Street",
  "Maidan",
  "Rabindra Sadan",
  "Kalighat",
  "Jatin Das Park",
  "Netaji Bhavan",
  "Rabindra Sarobar",
  "Mahanayak Uttam Kumar",
  "Netaji",
  "Masterda Surya Sen",
  "Gitanjali",
  "Kavi Nazrul",
  "Shahid Khudiram",
  "Kavi Subhash",
  "Sealdah",
  "Phoolbagan",
  "Salt Lake Stadium",
  "Bengal Chemical",
  "City Centre 1",
  "Karunamoyee",
  "Central Park",
  "Milon Mela",
  "VIP Bazar",
  "Barun Sengupta",
  "Howrah Maidan",
  "Howrah",
  "Mahakaran",
  "Joka",
  "Thakurpukur",
  "Sakherbazar",
  "Behala Chowrasta",
  "Behala Bazar",
  "Taratala",
  "Majerhat",
  "Mominpur",
  "Kidderpore",
  "Victoria",
  "Barasat",
  "Hridaypur",
  "Madhyamgram",
  "New Barrackpore",
  "Michael Nagar",
  "Biman Bandar",
  "Baranagar",
  "Noapara",
  "Bonhooghly",
  "Dakshineswar",
  "Khardaha",
  "Titagarh",
  "Barrackpore",
  "Satyajit Ray",
  "Hiland Park",
  "Ruby",
  "Science City",
  "Salt Lake Bypass",
  "Nicco Park",
  "Beliaghata",
  "Chingrighata",
];

